// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Question struct {
	ID           int32
	QuestionText string
	CreatedAt    sql.NullTime
}
