// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Option struct {
	ID          int32
	QuestionID  int32
	OptionText  string
	OptionIndex int16
	IsCorrect   bool
	CreatedAt   sql.NullTime
}

type Question struct {
	ID           int32
	QuestionText string
	CreatedAt    sql.NullTime
}
